### ISSUE TITLE
Edit Button Zimbra Distribution List Off Limits Firefox

### ISSUE THREAD

**Issue by cainelli** [inova-tecnologias/jenova-web#29]
Edit button at bottom of the page.

Firefox 48.0.1
Mac OS X El Capitan 10.11.6

![screen shot 2016-09-19 at 12 30 45](https://cloud.githubusercontent.com/assets/3514984/18638052/0632c7fc-7e65-11e6-8d89-b36e776e3c68.png)

**Comment by pagottoo** [comment]
fixed
